[workspace]
resolver = "2"

members = [
    "piper/core",
    "piper/synth",
    "piper/models/vits",
    "piper-grpc",
    "cli",
    "pyper",
    "espeak-phonemizer",
    "sonic-sys",
    "audio-ops"
]

[patch.crates-io]
libtashkeel_base = { path = "./deps/libtashkeel/libtashkeel_base" }

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
