[package]
name = "piper-synth"
version = "0.1.0"
edition = "2021"

[dependencies]
piper-core = { path = "../core" }
sonic-sys = { path = "../../sonic-sys" }
wave-writer = { path = "../../wave-writer" }
