[package]
name = "piper-synth"
version = "0.2.0"
edition = "2021"

[dependencies]
piper-core = { path = "../core" }
sonic-sys = { path = "../../sonic-sys" }
audio-ops = { path = "../../audio-ops" }
rayon = "1.7.0"
once_cell = "1.18.0"
