[package]
name = "pyper"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyper"
crate-type = ["cdylib"]

[dependencies]
piper-model = { path = "../piper-model" }
piper-synth = { path = "../piper-synth" }

[dependencies.pyo3]
version = "0.18.1"
features = ["extension-module", "abi3-py37"]

