[package]
name = "libtashkeel"
version = "1.2.0"
authors = ["Musharraf Omer<ibnomer2011@hotmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
description = "Arabic-text diacritic restoration using neural networks"
repository = "https://github.com/mush42/libtashkeel"
documentation = "https://github.com/mush42/libtashkeel"

[lib]
name = "libtashkeel"
crate-type = ["cdylib"]

[features]
ort = ["libtashkeel_base/ort"]
tract = ["libtashkeel_base/tract"]
default = ["ort"]

[dependencies]
ffi-support = "0.4.4"
libc = "0.2.147"
once_cell = "1.18.0"

[dependencies.libtashkeel_base]
path = "../libtashkeel_base"
default-features = false
